const avatars = [
  "👨‍🔬", "👮", "🧑‍🚀", "🧙", "🧛", "🧟", "🥷",
  "🦁", "🦊", "🐺", "🐻", "🐼", "🦉", "🦒", "🦈",
  "🤠", "😎", "🤓", "👺", "😈", "👻", "🤡",
  "🤖", "👽", "👾", "🐲"
];

const funnyTitles = [
  // --- المبتدئين والضائعين ---
  "الضايع المبتديء 😶",
  "راعي الهبد 🎲", // للشخص اللي يرمي كلام عشوائي
  "المزهرية 🏺", // للشخص الساكت طول اللعبة
  "النايم بالعسل 😴",
  "الضحية السهلة 🏳️", // اللي دايم يصوتون ضده أول واحد
  "البريء 😇",

  // --- المحققين والشكاكين ---
  "المحقق المتدرب 🔍",
  "كاشف السوالف 🔎",
  "كونان 👓",
  "الرادار 📡", // اللي يصيد الكذاب بسرعة
  "الشكاك 🤨", // اللي يشك في خياله
  "وكيل النيابة ⚖️", // اللي بس يسأل أسئلة

  // --- المموهين والمراوغين ---
  "المراوغ الأسطوري 🤺",
  "ملك التمويه 🎭",
  "العميل السري 🕵️‍♂️",
  "الثعلب المكار 🦊",
  "الوجه البريء 🥺", // شكله طيب بس هو الجاسوس
  "السوسة 🐛", // لقب للشخص اللي يفتن ويخرب
  "الساحر 🎩",

  // --- المتكلمين والفلاسفة ---
  "راعي الفزعة 🤝",
  "فيلسوف الجلسة 📜", // اللي يحلل زيادة عن اللزوم
  "الحكواتي 🗣️",
  "محامي الدفاع 💼", // اللي يدافع عن الجاسوس بالغلط
  "صايد الجو 😎",

  // --- الأساطير والوحوش ---
  "الذيب 🐺",
  "البروفيسور 👨‍🏫",
  "أسطورة السوالف 🏆",
  "الداهية 🧠",
  "الزعيم 👑",
  "القناص 🎯"
];

const roleNamesMap = { 'in': '🕵️ محقق', 'out': '😶‍🌫️‍ الضايع', 'agent': '🎭 عميل', 'undercover': '🤫 المموه' };

const categoryGroups = {
  "معلومات عامة": [
    { id: "دول", emoji: "🌍" },
    { id: "عواصم", emoji: "🏙️" },
    { id: "عملات", emoji: "💰" },
    { id: "مهن", emoji: "👨‍⚕️" },
    { id: "ماركات عالمية", emoji: "™️" },
    { id: "ماركات سيارات", emoji: "🚗" },
    { id: "وسائل نقل", emoji: "🚀" },
    { id: "طعام", emoji: "🍕" },
    { id: "أدوات منزلية", emoji: "🛋️" }
  ],
  "طبيعة وعلوم": [
    { id: "حيوانات", emoji: "🦁" },
    { id: "حشرات", emoji: "🐝" },
    { id: "زواحف", emoji: "🦎" },
    { id: "فواكه", emoji: "🍎" },
    { id: "خضروات", emoji: "🥦" },
    { id: "نباتات", emoji: "🌿" },
    { id: "ظواهر طبيعية", emoji: "🌋" },
    { id: "فضاء وكواكب", emoji: "🪐" },
    { id: "أعضاء الجسم", emoji: "🫀" }
  ],
  "ترفيه وفنون": [
    { id: "ألعاب فيديو", emoji: "🎮" },
    { id: "رياضة", emoji: "⚽" },
    { id: "أندية كرة قدم", emoji: "🏆" },
    { id: "أفلام", emoji: "🎬" },
    { id: "مسلسلات", emoji: "📺" },
    { id: "أبطال خارقون", emoji: "🦸‍♂️" },
    { id: "شخصيات كرتونية", emoji: "👾" },
    { id: "أنمي", emoji: "⛩️" },
    { id: "آلات موسيقية", emoji: "🎸" },
    { id: "تطبيقات", emoji: "📱" },
    { id: "ألوان", emoji: "🎨" },
    { id: "هوايات", emoji: "🎣" }
  ],
  "أماكن وأشياء": [
    { id: "أماكن عامة", emoji: "🏥" },
    { id: "أماكن في المنزل", emoji: "🏠" },
    { id: "أماكن في المدرسة", emoji: "🏫" },
    { id: "أشياء في الحقيبة", emoji: "🎒" },
    { id: "أدوات مدرسية", emoji: "✏️" },
    { id: "مباني وإنشاءات", emoji: "🏗️" },
    { id: "أعياد ومناسبات", emoji: "🎉" },
    { id: "أجهزة إلكترونية", emoji: "💻" },
    { id: "مواد دراسية", emoji: "📚" }
  ],
  "تأليف": [
    { id: "كلمات خاصة", emoji: "✍️" }
  ]
};

const wordBank = {
  //معلومات عامة
  "دول": [
    { word: "العراق", related: "country_a" },
    { word: "اليمن", related: "country_a" },
    { word: "عمان", related: "country_a" },
    { word: "البحرين", related: "country_a" },
    { word: "السعودية", related: "country_a" },
    { word: "الإمارات", related: "country_a" },
    { word: "الكويت", related: "country_a" },
    { word: "قطر", related: "country_a" },

    { word: "الأردن", related: "country_b" },
    { word: "لبنان", related: "country_b" },
    { word: "فلسطين", related: "country_b" },
    { word: "سوريا", related: "country_b" },

    { word: "مصر", related: "country_c" },
    { word: "المغرب", related: "country_c" },
    { word: "تونس", related: "country_c" },
    { word: "الجزائر", related: "country_c" },
    { word: "السودان", related: "country_c" },
    { word: "ليبيا", related: "country_c" },

    { word: "نيجيريا", related: "country_d" },
    { word: "غانا", related: "country_d" },
    { word: "إثيوبيا", related: "country_d" },
    { word: "جنوب أفريقيا", related: "country_d" },
    { word: "جيبوتي", related: "country_d" },

    { word: "إندونيسيا", related: "country_e" },
    { word: "سنغافورة", related: "country_e" },
    { word: "ماليزيا", related: "country_e" },
    { word: "تايلاند", related: "country_e" },
    { word: "فيتنام", related: "country_e" },
    { word: "الفلبين", related: "country_e" },

    { word: "الصين", related: "country_f" },
    { word: "تايوان", related: "country_f" },
    { word: "هونج كونج", related: "country_f" },
    { word: "اليابان", related: "country_f" },
    { word: "كوريا الجنوبية", related: "country_f" },
    { word: "كوريا الشمالية", related: "country_f" },

    { word: "الهند", related: "country_g" },
    { word: "بنغلاديش", related: "country_g" },
    { word: "نيبال", related: "country_g" },
    { word: "باكستان", related: "country_g" },
    { word: "أفغانستان", related: "country_g" },
    { word: "اوزباكستان", related: "country_g" },
    { word: "كازاخستان", related: "country_g" },

    { word: "كندا", related: "country_h" },
    { word: "أمريكا", related: "country_h" },
    { word: "المكسيك", related: "country_h" },
    { word: "غواتيمالا", related: "country_h" },
    { word: "أستراليا", related: "country_h" },

    { word: "البرازيل", related: "country_i" },
    { word: "الأرجنتين", related: "country_i" },
    { word: "باراغواي", related: "country_i" },
    { word: "تشيلي", related: "country_i" },
    { word: "أوروغواي", related: "country_i" },
    { word: "كولومبيا", related: "country_i" },

    { word: "روسيا", related: "country_j" },
    { word: "بريطانيا", related: "country_j" },
    { word: "فرنسا", related: "country_j" },
    { word: "إيطاليا", related: "country_j" },
    { word: "ألمانيا", related: "country_j" },
    { word: "إسبانيا", related: "country_j" },
    { word: "تركيا", related: "country_j" },
    { word: "أوكرانيا", related: "country_j" },
    { word: "اليونان", related: "country_j" },
    { word: "سويسرا", related: "country_j" },
    { word: "هولندا", related: "country_j" },
    { word: "السويد", related: "country_j" },
    { word: "البرتغال", related: "country_j" }
  ],
  "عواصم": [
    { word: "الرياض", related: "capital_a" },
    { word: "أبوظبي", related: "capital_a" },
    { word: "الكويت", related: "capital_a" },
    { word: "الدوحة", related: "capital_a" },
    { word: "المنامة", related: "capital_a" },
    { word: "مسقط", related: "capital_a" },
    { word: "بغداد", related: "capital_a" },
    { word: "صنعاء", related: "capital_a" },

    { word: "دمشق", related: "capital_b" },
    { word: "بيروت", related: "capital_b" },
    { word: "عمان", related: "capital_b" },
    { word: "القدس", related: "capital_b" },

    { word: "القاهرة", related: "capital_c" },
    { word: "الرباط", related: "capital_c" },
    { word: "الجزائر", related: "capital_c" },
    { word: "تونس", related: "capital_c" },
    { word: "طرابلس", related: "capital_c" },
    { word: "الخرطوم", related: "capital_c" },
    { word: "مقديشو", related: "capital_c" },
    { word: "أديس أبابا", related: "capital_c" },

    { word: "لندن", related: "capital_d" },
    { word: "باريس", related: "capital_d" },
    { word: "مدريد", related: "capital_d" },
    { word: "روما", related: "capital_d" },
    { word: "برلين", related: "capital_d" },
    { word: "أمستردام", related: "capital_d" },
    { word: "بروكسل", related: "capital_d" },
    { word: "فيينا", related: "capital_d" },
    { word: "أثينا", related: "capital_d" },
    { word: "لشبونة", related: "capital_d" },
    { word: "موسكو", related: "capital_d" },
    { word: "كييف", related: "capital_d" },
    { word: "أنقرة", related: "capital_d" },

    { word: "واشنطن", related: "capital_e" },
    { word: "أوتاوا", related: "capital_e" },
    { word: "مكسيكو سيتي", related: "capital_e" },
    { word: "برازيليا", related: "capital_e" },
    { word: "بوينس آيرس", related: "capital_e" },
    { word: "كانبرا", related: "capital_e" },

    { word: "طوكيو", related: "capital_f" },
    { word: "بكين", related: "capital_f" },
    { word: "سيول", related: "capital_f" },

    { word: "نيودلهي", related: "capital_f" },
    { word: "إسلام أباد", related: "capital_f" },
    { word: "جاكرتا", related: "capital_f" },
    { word: "كوالالمبور", related: "capital_f" },
    { word: "بانكوك", related: "capital_f" },
    { word: "مانيلا", related: "capital_f" },
    { word: "طهران", related: "capital_f" },
    { word: "هانوي", related: "capital_f" }
  ],
  "عملات": [
    { word: "ريال سعودي", related: "currency_a" },
    { word: "درهم إماراتي", related: "currency_a" },
    { word: "دينار كويتي", related: "currency_a" },
    { word: "ريال قطري", related: "currency_a" },
    { word: "ريال عماني", related: "currency_a" },
    { word: "دينار بحريني", related: "currency_a" },
    { word: "دينار عراقي", related: "currency_a" },
    { word: "ريال يمني", related: "currency_a" },

    { word: "دولار كندي", related: "currency_b" },
    { word: "دولار أسترالي", related: "currency_b" },
    { word: "دولار أمريكي", related: "currency_b" },

    { word: "يورو", related: "currency_b" },
    { word: "جنيه استرليني", related: "currency_b" },
    { word: "فرنك سويسري", related: "currency_b" },
    { word: "ين ياباني", related: "currency_b" },
    { word: "يوان صيني", related: "currency_b" },
    { word: "روبل روسي", related: "currency_b" },
    { word: "ليرة تركية", related: "currency_b" },

    { word: "دينار أردني", related: "currency_c" },
    { word: "ليرة لبنانية", related: "currency_c" },
    { word: "ليرة سورية", related: "currency_c" },
    { word: "جنيه فلسطيني", related: "currency_c" },

    { word: "جنيه سوداني", related: "currency_d" },
    { word: "درهم مغربي", related: "currency_d" },
    { word: "دينار جزائري", related: "currency_d" },
    { word: "دينار تونسي", related: "currency_d" },
    { word: "دينار ليبي", related: "currency_d" },
    { word: "بير إثيوبي", related: "currency_d" },

    { word: "روبية هندية", related: "currency_e" },
    { word: "تومان إيراني", related: "currency_e" },
    { word: "روبية باكستانية", related: "currency_e" },
    { word: "روبية إندونيسية", related: "currency_e" },
    { word: "رينغيت ماليزي", related: "currency_e" },
    { word: "بات تايلاندي", related: "currency_e" },
    { word: "بيزو فلبيني", related: "currency_e" },
    { word: "وون كوري", related: "currency_e" },
    { word: "دولار سنغافوري", related: "currency_e" },
    { word: "دولار هونج كونج", related: "currency_e" },

    { word: "ريال برازيلي", related: "currency_f" },
    { word: "بيزو مكسيكي", related: "currency_f" },
    { word: "بيزو أرجنتيني", related: "currency_f" },

    { word: "بيتكوين", related: "currency_g" },
    { word: "ذهب", related: "currency_g" },
    { word: "فضة", related: "currency_g" }
  ],
  "مهن": [
    { word: "طبيب", related: "jobs_a" },
    { word: "طبيب أسنان", related: "jobs_a" },
    { word: "صيدلي", related: "jobs_a" },
    { word: "ممرض", related: "jobs_a" },
    { word: "بيطري", related: "jobs_a" },

    { word: "مهندس", related: "jobs_b" },
    { word: "مبرمج", related: "jobs_b" },
    { word: "عالم", related: "jobs_b" },
    { word: "رائد فضاء", related: "jobs_b" },
    { word: "غواص", related: "jobs_b" },

    { word: "معلم", related: "jobs_c" },
    { word: "محامي", related: "jobs_c" },
    { word: "قاضي", related: "jobs_c" },
    { word: "محاسب", related: "jobs_c" },
    { word: "مدير", related: "jobs_c" },
    { word: "روائي", related: "jobs_c" },

    { word: "طيار", related: "jobs_d" },
    { word: "مضيف طيران", related: "jobs_d" },
    { word: "سائق", related: "jobs_d" },
    { word: "ساعي بريد", related: "jobs_d" },

    { word: "شرطي", related: "jobs_e" },
    { word: "جندي", related: "jobs_e" },
    { word: "إطفائي", related: "jobs_e" },
    { word: "حارس أمن", related: "jobs_e" },
    { word: "عامل نظافة", related: "jobs_e" },

    { word: "ميكانيكي", related: "jobs_f" },
    { word: "نجار", related: "jobs_f" },
    { word: "سباك", related: "jobs_f" },
    { word: "كهربائي", related: "jobs_f" },
    { word: "حداد", related: "jobs_f" },
    { word: "عامل بناء", related: "jobs_f" },
    { word: "خياط", related: "jobs_f" },
    { word: "صائغ", related: "jobs_f" },

    { word: "رسام", related: "jobs_g" },
    { word: "مصور", related: "jobs_g" },
    { word: "صحفي", related: "jobs_g" },
    { word: "ممثل", related: "jobs_g" },
    { word: "مغني", related: "jobs_g" },
    { word: "لاعب كرة", related: "jobs_g" },
    { word: "حكم", related: "jobs_g" },
    { word: "مدرب", related: "jobs_g" },

    { word: "طباخ", related: "jobs_h" },
    { word: "جزار", related: "jobs_h" },
    { word: "خباز", related: "jobs_h" },
    { word: "جرسون", related: "jobs_h" },
    { word: "بائع", related: "jobs_h" },
    { word: "حلاق", related: "jobs_h" },
    { word: "فلاح", related: "jobs_h" },
    { word: "بستاني", related: "jobs_h" },
    { word: "صياد", related: "jobs_h" }
  ],
  "ماركات عالمية": [
    { word: "أبل", related: "trademark_a" },
    { word: "سامسونج", related: "trademark_a" },
    { word: "جوجل", related: "trademark_a" },
    { word: "مايكروسوفت", related: "trademark_a" },
    { word: "سوني", related: "trademark_a" },
    { word: "ننتيندو", related: "trademark_a" },
    { word: "نيكون", related: "trademark_a" },
    { word: "كانون", related: "trademark_a" },

    { word: "أمازون", related: "trademark_b" },
    { word: "نتفليكس", related: "trademark_b" },
    { word: "يوتيوب", related: "trademark_b" },
    { word: "فيسبوك", related: "trademark_b" },
    { word: "انستقرام", related: "trademark_b" },
    { word: "واتساب", related: "trademark_b" },
    { word: "ديزني", related: "trademark_b" },

    { word: "فيزا", related: "trademark_c" },
    { word: "باي بال", related: "trademark_c" },
    { word: "أمريكان إكسبريس", related: "trademark_c" },
    { word: "ماستركارد", related: "trademark_c" },

    { word: "مكدونالدز", related: "trademark_d" },
    { word: "كنتاكي", related: "trademark_d" },
    { word: "ستاربكس", related: "trademark_d" },
    { word: "كوكاكولا", related: "trademark_d" },
    { word: "بيبسي", related: "trademark_d" },
    { word: "نستله", related: "trademark_d" },
    { word: "ريد بول", related: "trademark_d" },
    { word: "كيت كات", related: "trademark_d" }
  ],
  "ماركات سيارات": [
    { word: "تويوتا", related: "car_a" },
    { word: "هوندا", related: "car_a" },
    { word: "نيسان", related: "car_a" },
    { word: "مازدا", related: "car_a" },
    { word: "سوبارو", related: "car_a" },
    { word: "ميتسوبيشي", related: "car_a" },
    { word: "سوزوكي", related: "car_a" },
    { word: "ايسوزو", related: "car_a" },

    { word: "مرسيدس", related: "car_b" },
    { word: "بي إم دبليو", related: "car_b" },
    { word: "أودي", related: "car_b" },
    { word: "فولكس فاجن", related: "car_b" },
    { word: "بورش", related: "car_b" },

    { word: "فورد", related: "car_c" },
    { word: "شيفروليه", related: "car_c" },
    { word: "جي إم سي", related: "car_c" },
    { word: "دودج", related: "car_c" },
    { word: "جيب", related: "car_c" },
    { word: "كرايسلر", related: "car_c" },
    { word: "رام", related: "car_c" },

    { word: "لاند روفر", related: "car_d" },
    { word: "جاكوار", related: "car_d" },
    { word: "ميني كوبر", related: "car_d" },
    { word: "فولفو", related: "car_d" },
    { word: "ألفا روميو", related: "car_d" },
    { word: "فيات", related: "car_d" },
    { word: "بيجو", related: "car_d" },
    { word: "رينو", related: "car_d" },

    { word: "رولز رويس", related: "car_e" },
    { word: "بنتلي", related: "car_e" },
    { word: "لكزس", related: "car_e" },
    { word: "كاديلاك", related: "car_e" },
    { word: "لينكون", related: "car_e" },
    { word: "إنفينيتي", related: "car_e" },

    { word: "فيراري", related: "car_f" },
    { word: "لامبورغيني", related: "car_f" },
    { word: "مكلارين", related: "car_f" },
    { word: "أستون مارتن", related: "car_f" },
    { word: "بوجاتي", related: "car_f" },
    { word: "مازيراتي", related: "car_f" },

    { word: "تسلا", related: "car_g" },
    { word: "لوسيد", related: "car_g" },
    { word: "بي واي دي", related: "car_g" },
    { word: "شانجان", related: "car_g" },
    { word: "إم جي", related: "car_g" }
  ],
  "وسائل نقل": [
    { word: "سيارة", related: "transport_a" },
    { word: "حافلة", related: "transport_a" },
    { word: "شاحنة", related: "transport_a" },
    { word: "دراجة نارية", related: "transport_a" },
    { word: "دراجة هوائية", related: "transport_a" },
    { word: "تاكسي", related: "transport_a" },
    { word: "عربة", related: "transport_a" },
    { word: "إسعاف", related: "transport_a" },

    { word: "طائرة", related: "transport_b" },
    { word: "مروحية", related: "transport_b" },
    { word: "منطاد", related: "transport_b" },
    { word: "صاروخ", related: "transport_b" },
    { word: "مكوك فضاء", related: "transport_b" },
    { word: "طائرة نفاثة", related: "transport_b" },
    { word: "طائرة مسيرة", related: "transport_b" },

    { word: "سفينة", related: "transport_c" },
    { word: "قارب", related: "transport_c" },
    { word: "غواصة", related: "transport_c" },
    { word: "ناقلة نفط", related: "transport_c" },
    { word: "يخت", related: "transport_c" },
    { word: "عبارة", related: "transport_c" },
    { word: "جت سكي", related: "transport_c" },

    { word: "قطار", related: "transport_d" },
    { word: "مترو", related: "transport_d" },
    { word: "ترام", related: "transport_d" },
    { word: "قطار سريع", related: "transport_d" },
    { word: "سكوتر", related: "transport_d" },
    { word: "تلفريك", related: "transport_d" },
    { word: "رافعة", related: "transport_d" }
  ],
  "طعام": [
    { word: "كبسة", related: "food_a" },
    { word: "مطبق", related: "food_a" },
    { word: "جريش", related: "food_a" },
    { word: "مقلوبة", related: "food_a" },
    { word: "منسف", related: "food_a" },
    { word: "مسخن", related: "food_a" },
    { word: "ملوخية", related: "food_a" },
    { word: "كشري", related: "food_a" },
    { word: "رز", related: "food_a" },
    { word: "دجاج", related: "food_a" },
    { word: "لحم", related: "food_a" },

    { word: "برجر", related: "food_b" },
    { word: "بيتزا", related: "food_b" },
    { word: "شاورما", related: "food_b" },
    { word: "ستيك", related: "food_b" },
    { word: "كباب", related: "food_b" },
    { word: "سوشي", related: "food_b" },
    { word: "مكرونة", related: "food_b" },
    { word: "إندومي", related: "food_b" },
    { word: "بطاطس مقلية", related: "food_b" },

    { word: "فول", related: "food_c" },
    { word: "فلافل", related: "food_c" },
    { word: "حمص", related: "food_c" },
    { word: "بيض", related: "food_c" },
    { word: "شكشوكة", related: "food_c" },
    { word: "تميس", related: "food_c" },
    { word: "معصوب", related: "food_c" },
    { word: "جبن", related: "food_c" },
    { word: "خبز", related: "food_c" },

    { word: "كنافة", related: "food_d" },
    { word: "بقلاوة", related: "food_d" },
    { word: "بسبوسة", related: "food_d" },
    { word: "لقيمات", related: "food_d" },
    { word: "كليجا", related: "food_d" },
    { word: "شوكلاته", related: "food_d" },
    { word: "آيس كريم", related: "food_d" },
    { word: "دونات", related: "food_d" },
    { word: "بان كيك", related: "food_d" },

    { word: "سلطة", related: "food_e" },
    { word: "شوربة", related: "food_e" },
    { word: "سمبوسة", related: "food_e" },
    { word: "ورق عنب", related: "food_e" },
    { word: "فشار", related: "food_e" },
    { word: "تمر", related: "food_e" },
    { word: "عسل", related: "food_e" },
    { word: "بطيخ", related: "food_e" },
    { word: "كورن فليكس", related: "food_e" },
    { word: "سمك", related: "food_e" },
    { word: "جمبري", related: "food_e" }
  ],
  "أدوات منزلية": [
    { word: "ثلاجة", related: "home_items_a" },
    { word: "فرن", related: "home_items_a" },
    { word: "غسالة", related: "home_items_a" },
    { word: "نشافة", related: "home_items_a" },
    { word: "غسالة صحون", related: "home_items_a" },
    { word: "مكيف", related: "home_items_a" },
    { word: "دفاية", related: "home_items_a" },

    { word: "مايكرويف", related: "home_items_b" },
    { word: "قلاية هوائية", related: "home_items_b" },
    { word: "خلاط", related: "home_items_b" },
    { word: "توستر", related: "home_items_b" },
    { word: "صانعة قهوة", related: "home_items_b" },
    { word: "عجانة", related: "home_items_b" },
    { word: "مفرمة", related: "home_items_b" },
    { word: "شفاط", related: "home_items_b" },

    { word: "تلفزيون", related: "home_items_c" },
    { word: "رسيفر", related: "home_items_c" },
    { word: "بلايستيشن", related: "home_items_c" },
    { word: "سماعة", related: "home_items_c" },
    { word: "بروجيكتور", related: "home_items_c" },
    { word: "راوتر", related: "home_items_c" },

    { word: "مكنسة", related: "home_items_d" },
    { word: "مكواة", related: "home_items_d" },
    { word: "كواية بخار", related: "home_items_d" },
    { word: "سشوار", related: "home_items_d" },
    { word: "مكينة حلاقة", related: "home_items_d" },
    { word: "ممسحة أرض", related: "home_items_d" },

    { word: "لمبة", related: "home_items_e" },
    { word: "أباجورة", related: "home_items_e" },
    { word: "فيش", related: "home_items_e" },
    { word: "توصيلة", related: "home_items_e" },
    { word: "شاحن", related: "home_items_e" },

    { word: "دريل", related: "home_items_f" },
    { word: "مفك", related: "home_items_f" },
    { word: "شاكوش", related: "home_items_f" },
    { word: "زرادية", related: "home_items_f" },
    { word: "منشار", related: "home_items_f" },
    { word: "سلم", related: "home_items_f" },
    { word: "متر", related: "home_items_f" },
    { word: "خرطوم", related: "home_items_f" },

    { word: "مروحة", related: "home_items_g" },
    { word: "برادة ماء", related: "home_items_g" },
    { word: "كاميرا مراقبة", related: "home_items_g" },
    { word: "جرس باب", related: "home_items_g" },
    { word: "ميزان", related: "home_items_g" },
    { word: "ساعة حائط", related: "home_items_g" },
    { word: "سطل", related: "home_items_g" }
  ],

  //طبيعة وعلوم
  "حيوانات": [
    { word: "أسد", related: "animals_a" },
    { word: "نمر", related: "animals_a" },
    { word: "ذئب", related: "animals_a" },
    { word: "ثعلب", related: "animals_a" },
    { word: "دب", related: "animals_a" },
    { word: "تمساح", related: "animals_a" },
    { word: "فهد", related: "animals_a" },

    { word: "خروف", related: "animals_b" },
    { word: "ماعز", related: "animals_b" },
    { word: "بقرة", related: "animals_b" },
    { word: "حصان", related: "animals_b" },
    { word: "حمار", related: "animals_b" },
    { word: "جمل", related: "animals_b" },
    { word: "قطة", related: "animals_b" },
    { word: "كلب", related: "animals_b" },
    { word: "أرنب", related: "animals_b" },

    { word: "صقر", related: "animals_c" },
    { word: "نسر", related: "animals_c" },
    { word: "غراب", related: "animals_c" },
    { word: "بومة", related: "animals_c" },
    { word: "ببغاء", related: "animals_c" },
    { word: "نعامة", related: "animals_c" },
    { word: "دجاجة", related: "animals_c" },
    { word: "طاووس", related: "animals_c" },
    { word: "بطريق", related: "animals_c" },
    { word: "بجعة", related: "animals_c" },

    { word: "حوت", related: "animals_d" },
    { word: "قرش", related: "animals_d" },
    { word: "دولفين", related: "animals_d" },
    { word: "أخطبوط", related: "animals_d" },

    { word: "فيل", related: "animals_e" },
    { word: "زرافة", related: "animals_e" },
    { word: "قرد", related: "animals_e" },
    { word: "باندا", related: "animals_e" },
    { word: "كنغر", related: "animals_e" },
    { word: "غزال", related: "animals_e" },
    { word: "قنفذ", related: "animals_e" },
    { word: "سلحفاة", related: "animals_e" },
    { word: "ضفدع", related: "animals_e" },
    { word: "حمار وحشي", related: "animals_e" },
    { word: "خفاش", related: "animals_e" },
    { word: "فأر", related: "animals_e" }
  ],
  "حشرات": [
    { word: "فراشة", related: "insects_a" },
    { word: "نحلة", related: "insects_a" },
    { word: "يعسوب", related: "insects_a" },
    { word: "دعسوقة", related: "insects_a" },
    { word: "عثة", related: "insects_a" },

    { word: "ذبابة", related: "insects_b" },
    { word: "بعوضة", related: "insects_b" },
    { word: "صرصور", related: "insects_b" },
    { word: "برغوث", related: "insects_b" },
    { word: "قملة", related: "insects_b" },
    { word: "بق", related: "insects_b" },

    { word: "نملة", related: "insects_c" },
    { word: "نحل طنان", related: "insects_c" },
    { word: "دبور", related: "insects_c" },
    { word: "نمل أبيض", related: "insects_c" },
    { word: "جراد", related: "insects_c" },
    { word: "صرصور الليل", related: "insects_c" },
    { word: "خنفساء", related: "insects_d" },
    { word: "يرقة", related: "insects_d" }
  ],
  "زواحف": [
    { word: "ثعبان", related: "reptiles_a" },
    { word: "أفعى", related: "reptiles_a" },
    { word: "كوبرا", related: "reptiles_a" },
    { word: "أناكوندا", related: "reptiles_a" },

    { word: "سلحفاة", related: "reptiles_b" },
    { word: "سلحفاة بحرية", related: "reptiles_b" },
    { word: "تمساح", related: "reptiles_b" },
    { word: "قاطور", related: "reptiles_b" },

    { word: "سحلية", related: "reptiles_c" },
    { word: "حرباء", related: "reptiles_c" },
    { word: "ضب", related: "reptiles_c" },
    { word: "برص", related: "reptiles_c" },
    { word: "إغوانا", related: "reptiles_c" },
    { word: "تنين كومودو", related: "reptiles_c" }
  ],
  "فواكه": [
    { word: "تفاح", related: "fruits_a" },
    { word: "موز", related: "fruits_a" },
    { word: "عنب", related: "fruits_a" },
    { word: "كرز", related: "fruits_a" },
    { word: "خوخ", related: "fruits_a" },
    { word: "مشمش", related: "fruits_a" },
    { word: "كمثرى", related: "fruits_a" },
    { word: "تين", related: "fruits_a" },

    { word: "برتقال", related: "fruits_b" },
    { word: "ليمون", related: "fruits_b" },
    { word: "أناناس", related: "fruits_b" },
    { word: "مانجو", related: "fruits_b" },
    { word: "جوافة", related: "fruits_b" },
    { word: "كيوي", related: "fruits_b" },

    { word: "بطيخ", related: "fruits_c" },
    { word: "فراولة", related: "fruits_c" },
    { word: "توت", related: "fruits_c" },
    { word: "رمان", related: "fruits_c" }
  ],
  "خضروات": [
    { word: "طماطم", related: "vegetables_a" },
    { word: "خيار", related: "vegetables_a" },
    { word: "باذنجان", related: "vegetables_a" },
    { word: "فلفل بارد", related: "vegetables_a" },
    { word: "كوسة", related: "vegetables_a" },
    { word: "بامية", related: "vegetables_a" },
    { word: "فاصوليا", related: "vegetables_a" },
    { word: "يقطين", related: "vegetables_a" },

    { word: "بصل", related: "vegetables_b" },
    { word: "ثوم", related: "vegetables_b" },
    { word: "جزر", related: "vegetables_b" },
    { word: "بطاطس", related: "vegetables_b" },
    { word: "زنجبيل", related: "vegetables_b" },

    { word: "خس", related: "vegetables_c" },
    { word: "جرجير", related: "vegetables_c" },
    { word: "بقدونس", related: "vegetables_c" },
    { word: "زهرة", related: "vegetables_c" }
  ],
  "نباتات": [
    { word: "ورد جوري", related: "plants_a" },
    { word: "ياسمين", related: "plants_a" },
    { word: "لافندر", related: "plants_a" },

    { word: "نخلة", related: "plants_b" },
    { word: "شجرة زيتون", related: "plants_b" },
    { word: "شجرة تفاح", related: "plants_b" },
    { word: "صنوبر", related: "plants_b" },

    { word: "صبار", related: "plants_c" },
    { word: "نعناع", related: "plants_c" },
    { word: "ريحان", related: "plants_c" },
    { word: "عشب", related: "plants_c" },
    { word: "فطر", related: "plants_c" }
  ],
  "ظواهر طبيعية": [
    { word: "مطر", related: "natural_phenomena_a" },
    { word: "ثلج", related: "natural_phenomena_a" },
    { word: "برق", related: "natural_phenomena_a" },
    { word: "رعد", related: "natural_phenomena_a" },
    { word: "ضباب", related: "natural_phenomena_a" },
    { word: "برد", related: "natural_phenomena_a" },
    { word: "نجم", related: "natural_phenomena_a" },
    { word: "مجرة", related: "natural_phenomena_a" },
    { word: "ثقب أسود", related: "natural_phenomena_a" },
    { word: "نيزك", related: "natural_phenomena_a" },
    { word: "كسوف", related: "natural_phenomena_a" },
    { word: "خسوف", related: "natural_phenomena_a" },

    { word: "بركان", related: "natural_phenomena_b" },
    { word: "زلزال", related: "natural_phenomena_b" },
    { word: "إعصار", related: "natural_phenomena_b" },
    { word: "فيضان", related: "natural_phenomena_b" },
    { word: "تسونامي", related: "natural_phenomena_b" },
    { word: "جفاف", related: "natural_phenomena_b" },
    { word: "عاصفة رملية", related: "natural_phenomena_b" },

    { word: "جبل", related: "natural_phenomena_c" },
    { word: "وادي", related: "natural_phenomena_c" },
    { word: "كهف", related: "natural_phenomena_c" },
    { word: "شلال", related: "natural_phenomena_c" },
    { word: "نهر جليدي", related: "natural_phenomena_c" },
    { word: "واحة", related: "natural_phenomena_c" },
    { word: "جزيرة", related: "natural_phenomena_c" },
    { word: "غابة", related: "natural_phenomena_c" },
    { word: "بحر", related: "natural_phenomena_c" },
    { word: "مستنقع", related: "natural_phenomena_c" },
    { word: "شعاب مرجانية", related: "natural_phenomena_c" },

    { word: "جاذبية", related: "natural_phenomena_d" },
    { word: "احتباس حراري", related: "natural_phenomena_d" },
    { word: "طبقة الأوزون", related: "natural_phenomena_d" },
    { word: "رطوبة", related: "natural_phenomena_d" },
    { word: "سراب", related: "natural_phenomena_d" },
    { word: "صدى", related: "natural_phenomena_d" }
  ],
  "فضاء وكواكب": [
    { word: "الشمس", related: "space_planets_a" },
    { word: "عطارد", related: "space_planets_a" },
    { word: "الزهرة", related: "space_planets_a" },
    { word: "الأرض", related: "space_planets_a" },
    { word: "المريخ", related: "space_planets_a" },
    { word: "المشتري", related: "space_planets_a" },
    { word: "زحل", related: "space_planets_a" },
    { word: "أورانوس", related: "space_planets_a" },
    { word: "نبتون", related: "space_planets_a" },
    { word: "بلوتو", related: "space_planets_a" },
    { word: "القمر", related: "space_planets_a" },

    { word: "نجم", related: "space_planets_b" },
    { word: "مجرة", related: "space_planets_b" },
    { word: "مجرة درب التبانة", related: "space_planets_b" },
    { word: "سديم", related: "space_planets_b" },
    { word: "ثقب أسود", related: "space_planets_b" },
    { word: "ثقب دودي", related: "space_planets_b" },
    { word: "الكون", related: "space_planets_b" },
    { word: "سنة ضوئية", related: "space_planets_b" },

    { word: "نيزك", related: "space_planets_c" },
    { word: "مذنب", related: "space_planets_c" },
    { word: "شهاب", related: "space_planets_c" },
    { word: "كويكب", related: "space_planets_c" },
    { word: "فوهة", related: "space_planets_c" },

    { word: "رائد فضاء", related: "space_planets_d" },
    { word: "صاروخ", related: "space_planets_d" },
    { word: "قمر صناعي", related: "space_planets_d" },
    { word: "تلسكوب", related: "space_planets_d" },
    { word: "محطة الفضاء", related: "space_planets_d" },
    { word: "مركبة فضائية", related: "space_planets_d" },
    { word: "مسبار", related: "space_planets_d" },
    { word: "بدلة فضاء", related: "space_planets_d" },
    { word: "منصة إطلاق", related: "space_planets_d" },

    { word: "جاذبية", related: "space_planets_e" },
    { word: "انعدام الوزن", related: "space_planets_e" },
    { word: "مدار", related: "space_planets_e" },
    { word: "غلاف جوي", related: "space_planets_e" },
    { word: "فراغ", related: "space_planets_e" },
    { word: "علم الفلك", related: "space_planets_e" },
    { word: "كسوف", related: "space_planets_e" },
    { word: "خسوف", related: "space_planets_e" },
    { word: "فضاء", related: "space_planets_e" },
    { word: "طبق طائر", related: "space_planets_e" }
  ],
  "أعضاء الجسم": [
    { word: "قلب", related: "body_organs_a" },
    { word: "مخ", related: "body_organs_a" },
    { word: "رئة", related: "body_organs_a" },
    { word: "معدة", related: "body_organs_a" },
    { word: "كبد", related: "body_organs_a" },
    { word: "كلية", related: "body_organs_a" },
    { word: "أمعاء", related: "body_organs_a" },
    { word: "حنجرة", related: "body_organs_a" },
    { word: "شريان", related: "body_organs_a" },
    { word: "وريد", related: "body_organs_a" },
    { word: "دم", related: "body_organs_a" },

    { word: "عين", related: "body_organs_b" },
    { word: "أذن", related: "body_organs_b" },
    { word: "أنف", related: "body_organs_b" },
    { word: "لسان", related: "body_organs_b" },
    { word: "أسنان", related: "body_organs_b" },
    { word: "شفايف", related: "body_organs_b" },
    { word: "خد", related: "body_organs_b" },
    { word: "ذقن", related: "body_organs_b" },
    { word: "حاجب", related: "body_organs_b" },
    { word: "رموش", related: "body_organs_b" },
    { word: "شعر", related: "body_organs_b" },

    { word: "عظام", related: "body_organs_c" },
    { word: "جمجمة", related: "body_organs_c" },
    { word: "عمود فقري", related: "body_organs_c" },
    { word: "قفص صدري", related: "body_organs_c" },
    { word: "مفصل", related: "body_organs_c" },
    { word: "عضلات", related: "body_organs_c" },
    { word: "جلد", related: "body_organs_c" },

    { word: "يد", related: "body_organs_d" },
    { word: "أصابع", related: "body_organs_d" },
    { word: "أظافر", related: "body_organs_d" },
    { word: "كتف", related: "body_organs_d" },
    { word: "كوع", related: "body_organs_d" },
    { word: "رقبة", related: "body_organs_d" },
    { word: "رجل", related: "body_organs_d" },
    { word: "فخذ", related: "body_organs_d" },
    { word: "ساق", related: "body_organs_d" },
    { word: "ركبة", related: "body_organs_d" },
    { word: "كعب", related: "body_organs_d" },
    { word: "بطن", related: "body_organs_d" },
    { word: "سرّة", related: "body_organs_d" }
  ],

  //ترفيه وفنون
  "ألعاب فيديو": [
    { word: "بلايستيشن", related: "video_games_a" },
    { word: "اكس بوكس", related: "video_games_a" },
    { word: "نينتندو سويتش", related: "video_games_a" },
    { word: "بي سي", related: "video_games_a" },
    { word: "بي أس بي", related: "video_games_a" },
    { word: "ستيم ديك", related: "video_games_a" },

    { word: "ببجي", related: "video_games_b" },
    { word: "فورتنايت", related: "video_games_b" },
    { word: "كود", related: "video_games_b" },
    { word: "باتلفيلد", related: "video_games_b" },
    { word: "أبيكس ليجندز", related: "video_games_b" },
    { word: "أوفرواتش", related: "video_games_b" },
    { word: "كاونتر سترايك", related: "video_games_b" },
    { word: "هالو", related: "video_games_b" },

    { word: "فيفا", related: "video_games_c" },
    { word: "بيس", related: "video_games_c" },
    { word: "روكيت ليج", related: "video_games_c" },
    { word: "نيد فور سبيد", related: "video_games_c" },
    { word: "فورزا", related: "video_games_c" },

    { word: "قراند", related: "video_games_d" },
    { word: "ريد ديد", related: "video_games_d" },
    { word: "قود أوف وار", related: "video_games_d" },
    { word: "ذا لاست أوف أس", related: "video_games_d" },
    { word: "أساسنز كريد", related: "video_games_d" },
    { word: "إلدن رينج", related: "video_games_d" },
    { word: "دارك سولز", related: "video_games_d" },
    { word: "ويتشر", related: "video_games_d" },
    { word: "تومب رايدر", related: "video_games_d" },
    { word: "ريزيدنت إيفل", related: "video_games_d" },
    { word: "سايلنت هيل", related: "video_games_d" },

    { word: "ماينكرافت", related: "video_games_e" },
    { word: "روبلوكس", related: "video_games_e" },
    { word: "ماريو", related: "video_games_e" },
    { word: "سونيك", related: "video_games_e" },
    { word: "كراش", related: "video_games_e" },
    { word: "بوكيمون", related: "video_games_e" },
    { word: "ليج أوف ليجندز", related: "video_games_e" },
    { word: "دوتا 2", related: "video_games_e" },
    { word: "أمونج أس", related: "video_games_e" },
    { word: "فول جايز", related: "video_games_e" },
    { word: "مورتال كومبات", related: "video_games_e" },
    { word: "ستريت فايتر", related: "video_games_e" },
    { word: "كلاش أوف كلانس", related: "video_games_e" },
    { word: "كلاش رويال", related: "video_games_e" }
  ],
  "رياضة": [
    { word: "كرة القدم", related: "sports_a" },
    { word: "كرة السلة", related: "sports_a" },
    { word: "كرة الطائرة", related: "sports_a" },
    { word: "كرة اليد", related: "sports_a" },
    { word: "كريكت", related: "sports_a" },
    { word: "بيسبول", related: "sports_a" },
    { word: "كرة القدم الأمريكية", related: "sports_a" },
    { word: "هوكي الجليد", related: "sports_a" },

    { word: "تنس", related: "sports_b" },
    { word: "تنس الطاولة", related: "sports_b" },
    { word: "ريشة طائرة", related: "sports_b" },
    { word: "جولف", related: "sports_b" },
    { word: "بولينج", related: "sports_b" },
    { word: "بلياردو", related: "sports_b" },
    { word: "رماية", related: "sports_b" },
    { word: "سهام", related: "sports_b" },
    { word: "شطرنج", related: "sports_b" },

    { word: "ملاكمة", related: "sports_c" },
    { word: "مصارعة", related: "sports_c" },
    { word: "جودو", related: "sports_c" },
    { word: "كاراتيه", related: "sports_c" },
    { word: "تايكوندو", related: "sports_c" },
    { word: "كونغ فو", related: "sports_c" },
    { word: "مبارزة", related: "sports_c" },
    { word: "سومو", related: "sports_c" },

    { word: "سباحة", related: "sports_d" },
    { word: "غطس", related: "sports_d" },
    { word: "كرة الماء", related: "sports_d" },
    { word: "ركوب الأمواج", related: "sports_d" },

    { word: "جري", related: "sports_e" },
    { word: "رفع أثقال", related: "sports_e" },
    { word: "كمال أجسام", related: "sports_e" },
    { word: "فورمولا 1", related: "sports_e" },
    { word: "رالي", related: "sports_e" },
    { word: "دراجات هوائية", related: "sports_e" },
    { word: "فروسية", related: "sports_e" },
    { word: "سباق الهجن", related: "sports_e" },
    { word: "تزلج على الجليد", related: "sports_e" },
    { word: "تسلق الجبال", related: "sports_e" }
  ],
  "أندية كرة قدم": [
    { word: "الهلال", related: "football_clubs_a" },
    { word: "النصر", related: "football_clubs_a" },
    { word: "الاتحاد", related: "football_clubs_a" },
    { word: "الأهلي السعودي", related: "football_clubs_a" },
    { word: "الشباب", related: "football_clubs_a" },
    { word: "الاتفاق", related: "football_clubs_a" },

    { word: "ريال مدريد", related: "football_clubs_b" },
    { word: "برشلونة", related: "football_clubs_b" },
    { word: "أتلتيكو مدريد", related: "football_clubs_b" },
    { word: "إشبيلية", related: "football_clubs_b" },

    { word: "مانشستر سيتي", related: "football_clubs_c" },
    { word: "ليفربول", related: "football_clubs_c" },
    { word: "أرسنال", related: "football_clubs_c" },
    { word: "مانشستر يونايتد", related: "football_clubs_c" },
    { word: "تشيلسي", related: "football_clubs_c" },
    { word: "توتنهام", related: "football_clubs_c" },
    { word: "نيوكاسل", related: "football_clubs_c" },

    { word: "يوفنتوس", related: "football_clubs_d" },
    { word: "إي سي ميلان", related: "football_clubs_d" },
    { word: "إنتر ميلان", related: "football_clubs_d" },
    { word: "نابولي", related: "football_clubs_d" },
    { word: "روما", related: "football_clubs_d" },
    { word: "بايرن ميونخ", related: "football_clubs_d" },
    { word: "بروسيا دورتموند", related: "football_clubs_d" },
    { word: "باير ليفركوزن", related: "football_clubs_d" },
    { word: "باريس سان جيرمان", related: "football_clubs_d" },
    { word: "مارسيليا", related: "football_clubs_d" },

    { word: "الأهلي المصري", related: "football_clubs_e" },
    { word: "الزمالك", related: "football_clubs_e" },
    { word: "الرجاء البيضاوي", related: "football_clubs_e" },
    { word: "الوداد البيضاوي", related: "football_clubs_e" },
    { word: "الترجي التونسي", related: "football_clubs_e" },
    { word: "العين", related: "football_clubs_e" },
    { word: "السد", related: "football_clubs_e" },

    { word: "أياكس", related: "football_clubs_f" },
    { word: "بنفيكا", related: "football_clubs_f" },
    { word: "بورتو", related: "football_clubs_f" },
    { word: "غلطة سراي", related: "football_clubs_f" },
    { word: "فنربخشة", related: "football_clubs_f" },
    { word: "انتر ميامي", related: "football_clubs_f" },
    { word: "بوكا جونيورز", related: "football_clubs_f" },
    { word: "ريفر بليت", related: "football_clubs_f" },
    { word: "سانتوس", related: "football_clubs_f" },
    { word: "فلامنجو", related: "football_clubs_f" },
    { word: "سلتيك", related: "football_clubs_f" }
  ],
  "أفلام": [
    { word: "تيتانيك", related: "movies_a" },
    { word: "العراب", related: "movies_a" },
    { word: "أفاتار", related: "movies_a" },
    { word: "ماتريكس", related: "movies_a" },
    { word: "إنسبشن", related: "movies_a" },
    { word: "إنترستيلر", related: "movies_a" },
    { word: "هاري بوتر", related: "movies_a" },
    { word: "قراصنة الكاريبي", related: "movies_a" },
    { word: "مهمة مستحيلة", related: "movies_a" },
    { word: "جون ويك", related: "movies_a" },
    { word: "فاست أند فيورس", related: "movies_a" },
    { word: "روكي", related: "movies_a" },
    { word: "حديقة الديناصورات", related: "movies_a" },

    { word: "أفنجرز", related: "movies_b" },
    { word: "الجوكر", related: "movies_b" },
    { word: "سبايدرمان", related: "movies_b" },
    { word: "باتمان", related: "movies_b" },

    { word: "الأسد الملك", related: "movies_c" },
    { word: "توي ستوري", related: "movies_c" },
    { word: "نيمو", related: "movies_c" },
    { word: "شريك", related: "movies_c" },
    { word: "فروزن", related: "movies_c" },
    { word: "كونغ فو باندا", related: "movies_c" },
    { word: "هوم ألون", related: "movies_c" },

    { word: "الرسالة", related: "movies_d" },
    { word: "عمر المختار", related: "movies_d" },
    { word: "اللمبي", related: "movies_d" },
    { word: "سلام يا صاحبي", related: "movies_d" },
    { word: "مافيا", related: "movies_d" },
    { word: "زكي شان", related: "movies_d" },
    { word: "صعيدي في الجامعة", related: "movies_d" },
    { word: "غبي منه فيه", related: "movies_d" },
    { word: "بوحة", related: "movies_d" },
    { word: "الناظر", related: "movies_d" },
    { word: "عندليب الدقي", related: "movies_d" },
    { word: "إكس لارج", related: "movies_d" },
    { word: "فول الصين العظيم", related: "movies_d" },
    { word: "الفيل الأزرق", related: "movies_d" },

    { word: "سو", related: "movies_e" },
    { word: "سكريم", related: "movies_e" },
    { word: "إت", related: "movies_e" }
  ],
  "مسلسلات": [
    { word: "صراع العروش", related: "series_a" },
    { word: "بريكنج باد", related: "series_a" },
    { word: "لاكاسا دي بابيل", related: "series_a" },
    { word: "لعبة الحبار", related: "series_a" },
    { word: "سترينجر ثينقز", related: "series_a" },
    { word: "بريزون بريك", related: "series_a" },
    { word: "فريندز", related: "series_a" },
    { word: "ذا أوفيس", related: "series_a" },
    { word: "فايكنج", related: "series_a" },
    { word: "بيكي بلايندرز", related: "series_a" },
    { word: "لوست", related: "series_a" },
    { word: "ذا واكينق ديد", related: "series_a" },
    { word: "شيرلوك", related: "series_a" },
    { word: "بلاك ميرور", related: "series_a" },
    { word: "دارك", related: "series_a" },
    { word: "مستر روبوت", related: "series_a" },
    { word: "ذا كراون", related: "series_a" },
    { word: "ناركوس", related: "series_a" },
    { word: "وينزداي", related: "series_a" },
    { word: "ذا ويتشر", related: "series_a" },

    { word: "طاش ما طاش", related: "series_b" },
    { word: "شباب البومب", related: "series_b" },
    { word: "العاصوف", related: "series_b" },
    { word: "مسامير", related: "series_b" },
    { word: "رشاش", related: "series_b" },
    { word: "سكة سفر", related: "series_b" },
    { word: "منهو ولدنا", related: "series_b" },
    { word: "درب الزلق", related: "series_b" },
    { word: "خالتي قماشة", related: "series_b" },
    { word: "الحيالة", related: "series_b" },

    { word: "باب الحارة", related: "series_c" },
    { word: "الكبير أوي", related: "series_c" },
    { word: "رأفت الهجان", related: "series_c" },
    { word: "لن أعيش في جلباب أبي", related: "series_c" },
    { word: "جعفر العمدة", related: "series_c" },
    { word: "الأسطورة", related: "series_c" },
    { word: "الاختيار", related: "series_c" },
    { word: "ليالي الحلمية", related: "series_c" },
    { word: "ضيعة ضايعة", related: "series_c" },
    { word: "مرايا", related: "series_c" },

    { word: "حريم السلطان", related: "series_d" },
    { word: "حب أعمى", related: "series_d" },
    { word: "الحفرة", related: "series_d" },
    { word: "الطائر المبكر", related: "series_d" },
    { word: "وادي الذئاب", related: "series_d" }
  ],
  "أبطال خارقون": [
    { word: "سبايدرمان", related: "superheroes_a" },
    { word: "آيرون مان", related: "superheroes_a" },
    { word: "ثور", related: "superheroes_a" },
    { word: "كابتن أمريكا", related: "superheroes_a" },
    { word: "هالك", related: "superheroes_a" },
    { word: "دكتور سترينج", related: "superheroes_a" },
    { word: "بلاك بانثر", related: "superheroes_a" },
    { word: "ولفرين", related: "superheroes_a" },
    { word: "ديدبول", related: "superheroes_a" },

    { word: "سوبرمان", related: "superheroes_b" },
    { word: "باتمان", related: "superheroes_b" },
    { word: "وندر وومان", related: "superheroes_b" },
    { word: "فلاش", related: "superheroes_b" },
    { word: "أكوامان", related: "superheroes_b" },
    { word: "سايبورغ", related: "superheroes_b" },
    { word: "روبن", related: "superheroes_b" },

    { word: "الأفنجرز", related: "superheroes_c" },
    { word: "فرقة العدالة", related: "superheroes_c" },
    { word: "إكس مان", related: "superheroes_c" },
    { word: "سلاحف النينجا", related: "superheroes_c" },
    { word: "باور رينجرز", related: "superheroes_c" }
  ],
  "شخصيات كرتونية": [
    { word: "سبونج بوب", related: "cartoon_characters_a" },
    { word: "بسيط", related: "cartoon_characters_a" },
    { word: "توم وجيري", related: "cartoon_characters_a" },
    { word: "دورا", related: "cartoon_characters_a" },
    { word: "غامبول", related: "cartoon_characters_a" },
    { word: "بن 10", related: "cartoon_characters_a" },
    { word: "فتيات القوة", related: "cartoon_characters_a" },
    { word: "سكوبي دو", related: "cartoon_characters_a" },
    { word: "السنافر", related: "cartoon_characters_a" },
    { word: "تيمون وبومبا", related: "cartoon_characters_a" },
    { word: "ميكي ماوس", related: "cartoon_characters_a" },
    { word: "بطوط", related: "cartoon_characters_a" },
    { word: "شريك", related: "cartoon_characters_a" },
    { word: "وودي", related: "cartoon_characters_a" },
    { word: "باز يطير", related: "cartoon_characters_a" },
    { word: "مستر بين", related: "cartoon_characters_a" },
    { word: "شان ذا شيب", related: "cartoon_characters_a" },

    { word: "ناروتو", related: "cartoon_characters_b" },
    { word: "لوفي", related: "cartoon_characters_b" },
    { word: "غوكو", related: "cartoon_characters_b" },
    { word: "بيكاتشو", related: "cartoon_characters_b" },
    { word: "كونان", related: "cartoon_characters_b" },
    { word: "القناص", related: "cartoon_characters_b" },
    { word: "كابتن ماجد", related: "cartoon_characters_b" },
    { word: "عدنان ولينا", related: "cartoon_characters_b" },
    { word: "جريندايزر", related: "cartoon_characters_b" },
    { word: "عبقور", related: "cartoon_characters_b" },
    { word: "أبطال الديجيتال", related: "cartoon_characters_b" },
    { word: "سابق ولاحق", related: "cartoon_characters_b" },
    { word: "ريمي", related: "cartoon_characters_b" },
    { word: "سالي", related: "cartoon_characters_b" },
    { word: "ماروكو", related: "cartoon_characters_b" },
    { word: "ماوكلي", related: "cartoon_characters_b" },
    { word: "سندباد", related: "cartoon_characters_b" },

    { word: "باتمان", related: "cartoon_characters_c" },
    { word: "سوبرمان", related: "cartoon_characters_c" },
    { word: "سبايدرمان", related: "cartoon_characters_c" },
    { word: "هالك", related: "cartoon_characters_c" },
    { word: "آيرون مان", related: "cartoon_characters_c" },
    { word: "ثور", related: "cartoon_characters_c" },
    { word: "كابتن أمريكا", related: "cartoon_characters_c" },
    { word: "الجوكر", related: "cartoon_characters_c" },
    { word: "ثانوس", related: "cartoon_characters_c" },

    { word: "النمر الوردي", related: "cartoon_characters_d" },
    { word: "باغز باني", related: "cartoon_characters_d" },
    { word: "تويتي", related: "cartoon_characters_d" },
    { word: "بباباي", related: "cartoon_characters_d" },
    { word: "سيمبسون", related: "cartoon_characters_d" },
    { word: "ماريو", related: "cartoon_characters_d" },
    { word: "سونيك", related: "cartoon_characters_d" },
    { word: "بو", related: "cartoon_characters_d" }
  ],
  "أنمي": [
    { word: "ون بيس", related: "anime_a" },
    { word: "ناروتو", related: "anime_a" },
    { word: "دراغون بول", related: "anime_a" },
    { word: "بليتش", related: "anime_a" },
    { word: "هنتر x هنتر", related: "anime_a" },
    { word: "جوجوتسو كايسن", related: "anime_a" },
    { word: "قاتل الشياطين", related: "anime_a" },
    { word: "بوكو نو هيرو", related: "anime_a" },
    { word: "بلاك كلوفر", related: "anime_a" },
    { word: "فايري تيل", related: "anime_a" },

    { word: "هجوم العمالقة", related: "anime_b" },
    { word: "مذكرة الموت", related: "anime_b" },
    { word: "المحقق كونان", related: "anime_b" },
    { word: "فول ميتال ألكيميست", related: "anime_b" },
    { word: "طوكيو غول", related: "anime_b" },
    { word: "ون بانش مان", related: "anime_b" },
    { word: "كود غياس", related: "anime_b" },
    { word: "فينلاند ساغا", related: "anime_b" },
    { word: "بيرسيرك", related: "anime_b" },
    { word: "مونستر", related: "anime_b" },

    { word: "جريندايزر", related: "anime_c" },
    { word: "عدنان ولينا", related: "anime_c" },
    { word: "كابتن ماجد", related: "anime_c" },
    { word: "أبطال الديجيتال", related: "anime_c" },
    { word: "بوكيمون", related: "anime_c" },
    { word: "يوغي يو", related: "anime_c" },
    { word: "سابق ولاحق", related: "anime_c" },
    { word: "القناص", related: "anime_c" },
    { word: "سلام دانك", related: "anime_c" },
    { word: "دروب ريمي", related: "anime_c" },
    { word: "جزيرة الكنز", related: "anime_c" },

    { word: "هايكيو", related: "anime_d" },
    { word: "كوروكو نو باسكت", related: "anime_d" },
    { word: "بلو لوك", related: "anime_d" },
    { word: "إيبو", related: "anime_d" },
    { word: "ياكوزا", related: "anime_d" },
    { word: "بليتش", related: "anime_d" },
    { word: "سباي x فاميلي", related: "anime_d" },
    { word: "سايكي كي", related: "anime_d" },
    { word: "دكتور ستون", related: "anime_d" },
    { word: "نيفرلاند الموعودة", related: "anime_d" }
  ],
  "آلات موسيقية": [
    { word: "عود", related: "musical_instruments_a" },
    { word: "قانون", related: "musical_instruments_a" },
    { word: "ربابة", related: "musical_instruments_a" },
    { word: "كمان", related: "musical_instruments_a" },
    { word: "جيتار", related: "musical_instruments_a" },
    { word: "جيتار كهربائي", related: "musical_instruments_a" },
    { word: "تشيلو", related: "musical_instruments_a" },

    { word: "ناي", related: "musical_instruments_b" },
    { word: "مزمار", related: "musical_instruments_b" },
    { word: "ساكسفون", related: "musical_instruments_b" },
    { word: "بوق", related: "musical_instruments_b" },
    { word: "فلوت", related: "musical_instruments_b" },
    { word: "كلارينيت", related: "musical_instruments_b" },
    { word: "أكورديون", related: "musical_instruments_b" },
    { word: "هارمونيكا", related: "musical_instruments_b" },

    { word: "طبلة", related: "musical_instruments_c" },
    { word: "دف", related: "musical_instruments_c" },
    { word: "مثلث", related: "musical_instruments_c" },

    { word: "بيانو", related: "musical_instruments_d" },
    { word: "أورج", related: "musical_instruments_d" }
  ],
  "تطبيقات": [
    { word: "واتساب", related: "apps_a" },
    { word: "تيليجرام", related: "apps_a" },
    { word: "ديسكورد", related: "apps_a" },
    { word: "سناب شات", related: "apps_a" },
    { word: "انستقرام", related: "apps_a" },
    { word: "تيك توك", related: "apps_a" },
    { word: "تويتر", related: "apps_a" },
    { word: "فيسبوك", related: "apps_a" },
    { word: "لينكد إن", related: "apps_a" },
    { word: "بنترست", related: "apps_a" },

    { word: "يوتيوب", related: "apps_b" },
    { word: "نتفليكس", related: "apps_b" },
    { word: "شاهد", related: "apps_b" },
    { word: "تويتش", related: "apps_b" },
    { word: "سبوتيفاي", related: "apps_b" },
    { word: "ساوند كلاود", related: "apps_b" },
    { word: "أنغامي", related: "apps_b" },
    { word: "شزام", related: "apps_b" },

    { word: "أوبر", related: "apps_c" },
    { word: "كريم", related: "apps_c" },
    { word: "طلبات", related: "apps_c" },
    { word: "هنقرستيشن", related: "apps_c" },
    { word: "جاهز", related: "apps_c" },
    { word: "مرسول", related: "apps_c" },
    { word: "حراج", related: "apps_c" },
    { word: "بوكينج", related: "apps_c" },
    { word: "إير بي إن بي", related: "apps_c" },

    { word: "جيميل", related: "apps_d" },
    { word: "خرائط جوجل", related: "apps_d" },
    { word: "ويز", related: "apps_d" },
    { word: "زوم", related: "apps_d" },
    { word: "تيمز", related: "apps_d" },
    { word: "جوجل درايف", related: "apps_d" },
    { word: "كانفا", related: "apps_d" },
    { word: "شات جي بي تي", related: "apps_d" },
    { word: "دولينجو", related: "apps_d" },

    { word: "أمازون", related: "apps_e" },
    { word: "نون", related: "apps_e" },
    { word: "شي إن", related: "apps_e" },
    { word: "نمشي", related: "apps_e" }
  ],
  "ألوان": [
    { word: "أحمر", related: "colors_a" },
    { word: "أزرق", related: "colors_a" },
    { word: "أصفر", related: "colors_a" },
    { word: "أخضر", related: "colors_a" },
    { word: "أسود", related: "colors_a" },
    { word: "أبيض", related: "colors_a" },
    { word: "بني", related: "colors_a" },
    { word: "رمادي", related: "colors_a" },

    { word: "برتقالي", related: "colors_b" },
    { word: "بنفسجي", related: "colors_b" },
    { word: "وردي", related: "colors_b" },
    { word: "سماوي", related: "colors_b" },
    { word: "كحلي", related: "colors_b" },
    { word: "عنابي", related: "colors_b" },
    { word: "عسلي", related: "colors_b" },

    { word: "ذهبي", related: "colors_c" },
    { word: "فضي", related: "colors_c" },
    { word: "نحاسي", related: "colors_c" },
    { word: "لؤلؤي", related: "colors_c" },
    { word: "برونزي", related: "colors_c" }
  ],
  "هوايات": [
    { word: "رسم", related: "hobbies_a" },
    { word: "تصوير", related: "hobbies_a" },
    { word: "خياطة", related: "hobbies_a" },
    { word: "حياكة", related: "hobbies_a" },
    { word: "صناعة الفخار", related: "hobbies_a" },
    { word: "نجارة", related: "hobbies_a" },
    { word: "غناء", related: "hobbies_a" },
    { word: "تمثيل", related: "hobbies_a" },
    { word: "رقص", related: "hobbies_a" },
    { word: "عزف جيتار", related: "hobbies_a" },
    { word: "عزف بيانو", related: "hobbies_a" },

    { word: "سباحة", related: "hobbies_b" },
    { word: "كرة القدم", related: "hobbies_b" },
    { word: "ركوب الخيل", related: "hobbies_b" },
    { word: "ركوب الدراجة", related: "hobbies_b" },
    { word: "جري", related: "hobbies_b" },
    { word: "غوص", related: "hobbies_b" },
    { word: "هايكنج", related: "hobbies_b" },
    { word: "تزلج", related: "hobbies_b" },
    { word: "بولينج", related: "hobbies_b" },
    { word: "بلياردو", related: "hobbies_b" },
    { word: "يوغا", related: "hobbies_b" },

    { word: "قراءة", related: "hobbies_c" },
    { word: "كتابة", related: "hobbies_c" },
    { word: "شطرنج", related: "hobbies_c" },
    { word: "بلوت", related: "hobbies_c" },
    { word: "حل ألغاز", related: "hobbies_c" },
    { word: "تجميع عملات", related: "hobbies_c" },
    { word: "تجميع طوابع", related: "hobbies_c" },
    { word: "تحف وأنتيك", related: "hobbies_c" },
    { word: "تأمل", related: "hobbies_c" },

    { word: "ألعاب فيديو", related: "hobbies_d" },
    { word: "برمجة", related: "hobbies_d" },
    { word: "تصميم جرافيك", related: "hobbies_d" },
    { word: "مونتاج", related: "hobbies_d" },
    { word: "ميكانيكا", related: "hobbies_d" },
    { word: "مشاهدة أفلام", related: "hobbies_d" },

    { word: "صيد السمك", related: "hobbies_e" },
    { word: "صقارة", related: "hobbies_e" },
    { word: "طبخ", related: "hobbies_e" },
    { word: "سفر", related: "hobbies_e" },
    { word: "زراعة", related: "hobbies_e" },
    { word: "تخييم", related: "hobbies_e" },
    { word: "مراقبة الطيور", related: "hobbies_e" },
    { word: "رصد النجوم", related: "hobbies_e" },
    { word: "ألعاب خفة", related: "hobbies_e" }
  ],

  //أماكن وأشياء
  "أماكن عامة": [
    { word: "مستشفى", related: "public_places_a" },
    { word: "صيدلية", related: "public_places_a" },
    { word: "مسجد", related: "public_places_a" },
    { word: "بنك", related: "public_places_a" },
    { word: "بريد", related: "public_places_a" },
    { word: "محطة بنزين", related: "public_places_a" },
    { word: "مغسلة ملابس", related: "public_places_a" },
    { word: "مغسلة سيارات", related: "public_places_a" },

    { word: "حديقة", related: "public_places_b" },
    { word: "شاطئ", related: "public_places_b" },
    { word: "ملاهي", related: "public_places_b" },
    { word: "حديقة حيوان", related: "public_places_b" },
    { word: "سيرك", related: "public_places_b" },
    { word: "نادي رياضي", related: "public_places_b" },
    { word: "ملعب", related: "public_places_b" },
    { word: "مسبح عام", related: "public_places_b" },
    { word: "سينما", related: "public_places_b" },
    { word: "مسرح", related: "public_places_b" },
    { word: "متحف", related: "public_places_b" },
    { word: "فندق", related: "public_places_b" },
    { word: "صالة أفراح", related: "public_places_b" },

    { word: "مدرسة", related: "public_places_c" },
    { word: "جامعة", related: "public_places_c" },
    { word: "مكتبة", related: "public_places_c" },
    { word: "مزرعة", related: "public_places_c" },
    { word: "محل ورد", related: "public_places_d" },

    { word: "مول", related: "public_places_d" },
    { word: "سوبرماركت", related: "public_places_d" },
    { word: "سوق شعبي", related: "public_places_d" },
    { word: "مطعم", related: "public_places_d" },
    { word: "مقهى", related: "public_places_d" },
    { word: "مخبز", related: "public_places_d" },
    { word: "حلاق", related: "public_places_d" },
    { word: "صالون تجميل", related: "public_places_d" },
    { word: "ورشة", related: "public_places_d" },
    { word: "معرض سيارات", related: "public_places_d" },
    { word: "مكتب عقار", related: "public_places_d" },
    { word: "محل ألعاب", related: "public_places_d" },
    { word: "محل جوالات", related: "public_places_d" },

    { word: "مطار", related: "public_places_e" },
    { word: "ميناء", related: "public_places_e" },
    { word: "محطة قطار", related: "public_places_e" },
    { word: "جسر", related: "public_places_e" },
    { word: "نفق", related: "public_places_e" },
    { word: "مركز شرطة", related: "public_places_e" },
    { word: "محكمة", related: "public_places_e" },
    { word: "سجن", related: "public_places_e" },
    { word: "سفارة", related: "public_places_e" },
    { word: "دفاع مدني", related: "public_places_e" },
    { word: "مصنع", related: "public_places_e" }
  ],
  "أماكن في المنزل": [
    { word: "مجلس", related: "places_house_a" },
    { word: "صالة", related: "places_house_a" },
    { word: "غرفة الضيوف", related: "places_house_a" },
    { word: "غرفة طعام", related: "places_house_a" },
    { word: "مدخل", related: "places_house_a" },
    { word: "مصلى", related: "places_house_a" },

    { word: "غرفة النوم", related: "places_house_b" },
    { word: "حمام", related: "places_house_b" },
    { word: "دورة مياه", related: "places_house_b" },
    { word: "مغاسل", related: "places_house_b" },
    { word: "غرفة ملابس", related: "places_house_b" },
    { word: "غرفة الغيار", related: "places_house_b" },
    { word: "مكتب", related: "places_house_b" },
    { word: "مكتبة", related: "places_house_b" },
    { word: "غرفة ألعاب", related: "places_house_b" },

    { word: "مطبخ", related: "places_house_c" },
    { word: "غرفة الغسيل", related: "places_house_c" },
    { word: "مخزن", related: "places_house_c" },
    { word: "خزانة أحذية", related: "places_house_c" },
    { word: "قبو", related: "places_house_c" },
    { word: "علية", related: "places_house_c" },
    { word: "غرفة الخادمة", related: "places_house_c" },
    { word: "غرفة السائق", related: "places_house_c" },

    { word: "حوش", related: "places_house_d" },
    { word: "حديقة", related: "places_house_d" },
    { word: "سطح", related: "places_house_d" },
    { word: "بلكونة", related: "places_house_d" },
    { word: "حوض سباحة", related: "places_house_d" },
    { word: "ملحق", related: "places_house_d" },
    { word: "مصعد", related: "places_house_d" }
  ],
  "أماكن في المدرسة": [
    { word: "فصل", related: "places_school_a" },
    { word: "معمل حاسب", related: "places_school_a" },
    { word: "مختبر علوم", related: "places_school_a" },
    { word: "مكتبة", related: "places_school_a" },
    { word: "غرفة الفنية", related: "places_school_a" },
    { word: "غرفة الموسيقى", related: "places_school_a" },
    { word: "قاعة الاختبارات", related: "places_school_a" },

    { word: "إدارة", related: "places_school_b" },
    { word: "غرفة المعلمين", related: "places_school_b" },
    { word: "غرفة الوكيل", related: "places_school_b" },
    { word: "غرفة المرشد", related: "places_school_b" },
    { word: "غرفة الاجتماعات", related: "places_school_b" },
    { word: "غرفة التصحيح", related: "places_school_b" },

    { word: "مقصف", related: "places_school_c" },
    { word: "مصلى", related: "places_school_c" },
    { word: "حمام", related: "places_school_c" },
    { word: "عيادة", related: "places_school_c" },
    { word: "غرفة الحارس", related: "places_school_c" },
    { word: "مخزن", related: "places_school_c" },

    { word: "ملعب", related: "places_school_d" },
    { word: "ساحة", related: "places_school_d" },
    { word: "مسرح", related: "places_school_d" },
    { word: "مواقف", related: "places_school_d" },
    { word: "مواقف المعلمين", related: "places_school_d" }
  ],
  "أشياء في الحقيبة": [
    { word: "جوال", related: "things_bag_a" },
    { word: "شاحن", related: "things_bag_a" },
    { word: "باور بانك", related: "things_bag_a" },
    { word: "سماعة", related: "things_bag_a" },
    { word: "لابتوب", related: "things_bag_a" },
    { word: "فلاش ميموري", related: "things_bag_a" },
    { word: "سلك شاحن", related: "things_bag_a" },
    { word: "ايباد", related: "things_bag_a" },

    { word: "عطر", related: "things_bag_b" },
    { word: "مناديل", related: "things_bag_b" },
    { word: "معقم", related: "things_bag_b" },
    { word: "كمامة", related: "things_bag_b" },
    { word: "مرطب شفايف", related: "things_bag_b" },
    { word: "مشط", related: "things_bag_b" },
    { word: "مرآة", related: "things_bag_b" },
    { word: "كريم يد", related: "things_bag_b" },
    { word: "مكياج", related: "things_bag_b" },
    { word: "ربطة شعر", related: "things_bag_b" },
    { word: "مزيل عرق", related: "things_bag_b" },
    { word: "قطرة عين", related: "things_bag_b" },
    { word: "مسواك", related: "things_bag_b" },
    { word: "مقص أظافر", related: "things_bag_b" },
    { word: "بنادول", related: "things_bag_b" },

    { word: "محفظة", related: "things_bag_c" },
    { word: "بطاقة صراف", related: "things_bag_c" },
    { word: "فلوس", related: "things_bag_c" },
    { word: "بطاقة عمل", related: "things_bag_c" },
    { word: "جواز سفر", related: "things_bag_c" },
    { word: "رخصة قيادة", related: "things_bag_c" },
    { word: "فاتورة", related: "things_bag_c" },
    { word: "مفتاح", related: "things_bag_c" },

    { word: "قلم", related: "things_bag_d" },
    { word: "دفتر", related: "things_bag_d" },
    { word: "كتاب", related: "things_bag_d" },
    { word: "نظارة", related: "things_bag_d" },
    { word: "نظارة شمسية", related: "things_bag_d" },
    { word: "ولاعة", related: "things_bag_d" },
    { word: "علك", related: "things_bag_d" },
    { word: "قارورة ماء", related: "things_bag_d" },
    { word: "سبحة", related: "things_bag_d" },
    { word: "دبوس", related: "things_bag_d" },
    { word: "خاتم", related: "things_bag_d" }
  ],
  "أدوات مدرسية": [
    { word: "قلم رصاص", related: "school_supplies_a" },
    { word: "قلم حبر", related: "school_supplies_a" },
    { word: "قلم سبورة", related: "school_supplies_a" },
    { word: "طباشير", related: "school_supplies_a" },
    { word: "مساحة", related: "school_supplies_a" },
    { word: "براية", related: "school_supplies_a" },
    { word: "مقلمة", related: "school_supplies_a" },

    { word: "مسطرة", related: "school_supplies_b" },
    { word: "فرجار", related: "school_supplies_b" },
    { word: "منقلة", related: "school_supplies_b" },
    { word: "آلة حاسبة", related: "school_supplies_b" },
    { word: "كراسة رسم", related: "school_supplies_b" },
    { word: "ألوان خشبية", related: "school_supplies_b" },
    { word: "ألوان مائية", related: "school_supplies_b" },
    { word: "ألوان شمعية", related: "school_supplies_b" },
    { word: "فرشاة رسم", related: "school_supplies_b" },
    { word: "صلصال", related: "school_supplies_b" },

    { word: "دفتر", related: "school_supplies_c" },
    { word: "كتاب", related: "school_supplies_c" },
    { word: "مصحف", related: "school_supplies_c" },
    { word: "قاموس", related: "school_supplies_c" },
    { word: "ملف", related: "school_supplies_c" },
    { word: "ورق ملاحظات", related: "school_supplies_c" },
    { word: "جدول حصص", related: "school_supplies_c" },
    { word: "خريطة", related: "school_supplies_c" },
    { word: "حقيبة", related: "school_supplies_c" },
    { word: "مجلد", related: "school_supplies_c" },

    { word: "سبورة", related: "school_supplies_d" },
    { word: "دباسة", related: "school_supplies_d" },
    { word: "خرامة", related: "school_supplies_d" },
    { word: "مقص", related: "school_supplies_d" },
    { word: "مشرط", related: "school_supplies_d" },
    { word: "غراء", related: "school_supplies_d" },
    { word: "مشبك ورق", related: "school_supplies_d" },
    { word: "دبوس", related: "school_supplies_d" },
    { word: "عدسة مكبرة", related: "school_supplies_d" },
    { word: "بطاقة طالب", related: "school_supplies_d" },
    { word: "فلاش ميموري", related: "school_supplies_d" }
  ],
  "مباني وإنشاءات": [
    { word: "برج خليفة", related: "buildings_a" },
    { word: "الكعبة", related: "buildings_a" },
    { word: "الأهرامات", related: "buildings_a" },
    { word: "سور الصين العظيم", related: "buildings_a" },
    { word: "برج إيفل", related: "buildings_a" },
    { word: "تمثال الحرية", related: "buildings_a" },
    { word: "بيج بن", related: "buildings_a" },
    { word: "برج بيزا المائل", related: "buildings_a" },
    { word: "تاج محل", related: "buildings_a" },
    { word: "البطراء", related: "buildings_a" },
    { word: "نصب تذكاري", related: "buildings_a" },

    { word: "مستشفى", related: "buildings_b" },
    { word: "مدرسة", related: "buildings_b" },
    { word: "جامعة", related: "buildings_b" },
    { word: "مطار", related: "buildings_b" },
    { word: "مسجد", related: "buildings_b" },
    { word: "بنك", related: "buildings_b" },
    { word: "متحف", related: "buildings_b" },
    { word: "مكتبة", related: "buildings_b" },
    { word: "سجن", related: "buildings_b" },
    { word: "محطة قطار", related: "buildings_b" },
    { word: "سينما", related: "buildings_b" },
    { word: "فندق", related: "buildings_b" },
    { word: "مول", related: "buildings_b" },
    { word: "محطة بنزين", related: "buildings_b" },

    { word: "قصر", related: "buildings_c" },
    { word: "قلعة", related: "buildings_c" },
    { word: "فيلا", related: "buildings_c" },
    { word: "عمارة", related: "buildings_c" },
    { word: "ناطحة سحاب", related: "buildings_c" },
    { word: "خيمة", related: "buildings_c" },
    { word: "كوخ", related: "buildings_c" },
    { word: "كوخ ثلجي", related: "buildings_c" },

    { word: "جسر", related: "buildings_d" },
    { word: "نفق", related: "buildings_d" },
    { word: "سد", related: "buildings_d" },
    { word: "مصنع", related: "buildings_d" },
    { word: "صومعة", related: "buildings_d" },
    { word: "طاحونة", related: "buildings_d" },
    { word: "منارة", related: "buildings_d" },
    { word: "برج مراقبة", related: "buildings_d" },
    { word: "مرصد فلكي", related: "buildings_d" },
    { word: "ملعب", related: "buildings_d" },
    { word: "ملعب كرة قدم", related: "buildings_d" }
  ],
  "أعياد ومناسبات": [
    { word: "عيد الفطر", related: "holidays_a" },
    { word: "عيد الأضحى", related: "holidays_a" },
    { word: "رمضان", related: "holidays_a" },
    { word: "يوم عرفة", related: "holidays_a" },
    { word: "ليلة القدر", related: "holidays_a" },
    { word: "الحج", related: "holidays_a" },
    { word: "عمرة", related: "holidays_a" },
    { word: "يوم الجمعة", related: "holidays_a" },
    { word: "عاشوراء", related: "holidays_a" },
    { word: "رأس السنة الهجرية", related: "holidays_a" },
    { word: "قرقيعان", related: "holidays_a" },

    { word: "اليوم الوطني", related: "holidays_b" },
    { word: "يوم التأسيس", related: "holidays_b" },
    { word: "رأس السنة الميلادية", related: "holidays_b" },
    { word: "معرض الكتاب", related: "holidays_b" },
    { word: "يوم الأم", related: "holidays_b" },
    { word: "يوم الأب", related: "holidays_b" },

    { word: "زواج", related: "holidays_c" },
    { word: "خطوبة", related: "holidays_c" },
    { word: "ذكرى زواج", related: "holidays_c" },
    { word: "يوم الميلاد", related: "holidays_c" },
    { word: "حفل تخرج", related: "holidays_c" },
    { word: "مولود جديد", related: "holidays_c" },
    { word: "ترقية", related: "holidays_c" },
    { word: "تقاعد", related: "holidays_c" },
    { word: "عزيمة", related: "holidays_c" },
    { word: "جمعة أهل", related: "holidays_c" },
    { word: "زيارة مريض", related: "holidays_c" },
    { word: "حفلة تنكرية", related: "holidays_c" },

    { word: "إجازة الصيف", related: "holidays_d" },
    { word: "إجازة الربيع", related: "holidays_d" },
    { word: "العودة للمدارس", related: "holidays_d" },
    { word: "اختبارات", related: "holidays_d" },
    { word: "كشتة", related: "holidays_d" }
  ],
  "أجهزة إلكترونية": [
    { word: "جوال", related: "electronic_devices_a" },
    { word: "لابتوب", related: "electronic_devices_a" },
    { word: "كمبيوتر مكتبي", related: "electronic_devices_a" },
    { word: "ايباد", related: "electronic_devices_a" },
    { word: "تابلت", related: "electronic_devices_a" },
    { word: "ساعة ذكية", related: "electronic_devices_a" },
    { word: "قارئ إلكتروني", related: "electronic_devices_a" },
    { word: "ماوس", related: "electronic_devices_a" },
    { word: "كيبورد", related: "electronic_devices_a" },
    { word: "طابعة", related: "electronic_devices_a" },
    { word: "راوتر", related: "electronic_devices_a" },

    { word: "تلفزيون", related: "electronic_devices_b" },
    { word: "بلايستيشن", related: "electronic_devices_b" },
    { word: "اكس بوكس", related: "electronic_devices_b" },
    { word: "نينتندو سويتش", related: "electronic_devices_b" },
    { word: "جيم بوي", related: "electronic_devices_b" },
    { word: "بروجيكتور", related: "electronic_devices_b" },
    { word: "رسيفر", related: "electronic_devices_b" },
    { word: "سماعة رأس", related: "electronic_devices_b" },
    { word: "سماعة أذن", related: "electronic_devices_b" },
    { word: "سبيكر", related: "electronic_devices_b" },
    { word: "مايكروفون", related: "electronic_devices_b" },
    { word: "راديو", related: "electronic_devices_b" },
    { word: "مشغل أسطوانات", related: "electronic_devices_b" },
    { word: "نظارة واقع افتراضي", related: "electronic_devices_b" },

    { word: "كاميرا", related: "electronic_devices_c" },
    { word: "درون", related: "electronic_devices_c" },
    { word: "كاميرا مراقبة", related: "electronic_devices_c" },
    { word: "داش كام", related: "electronic_devices_c" },
    { word: "شاحن متنقل", related: "electronic_devices_c" },
    { word: "فلاش ميموري", related: "electronic_devices_c" },
    { word: "هارد ديسك", related: "electronic_devices_c" },
    { word: "آلة حاسبة", related: "electronic_devices_c" },
    { word: "بيجر", related: "electronic_devices_c" },

    { word: "أليكسا", related: "electronic_devices_d" },
    { word: "روبوت مكنسة", related: "electronic_devices_d" },
    { word: "ميزان ذكي", related: "electronic_devices_d" },
    { word: "لمبة ذكية", related: "electronic_devices_d" },
    { word: "فيش ذكي", related: "electronic_devices_d" },
    { word: "مكينة قهوة", related: "electronic_devices_d" },
    { word: "غلاية ذكية", related: "electronic_devices_d" },

    { word: "ماكينة حلاقة", related: "electronic_devices_e" },
    { word: "سشوار", related: "electronic_devices_e" },
    { word: "مكواة شعر", related: "electronic_devices_e" },
    { word: "فرشاة أسنان كهربائية", related: "electronic_devices_e" },
    { word: "جهاز قياس الضغط", related: "electronic_devices_e" },
    { word: "جهاز السكر", related: "electronic_devices_e" },
    { word: "جهاز مشي", related: "electronic_devices_e" }
  ],
  "مواد دراسية": [
    { word: "رياضيات", related: "study_materials_a" },
    { word: "فيزياء", related: "study_materials_a" },
    { word: "كيمياء", related: "study_materials_a" },
    { word: "أحياء", related: "study_materials_a" },
    { word: "علوم", related: "study_materials_a" },
    { word: "جيولوجيا", related: "study_materials_a" },
    { word: "علم البيئة", related: "study_materials_a" },
    { word: "فلك", related: "study_materials_a" },

    { word: "قرآن", related: "study_materials_b" },
    { word: "نحو", related: "study_materials_b" },
    { word: "أدب", related: "study_materials_b" },
    { word: "إملاء", related: "study_materials_b" },
    { word: "إنجليزي", related: "study_materials_b" },
    { word: "فرنسي", related: "study_materials_b" },
    { word: "صيني", related: "study_materials_b" },

    { word: "تاريخ", related: "study_materials_c" },
    { word: "جغرافيا", related: "study_materials_c" },
    { word: "اجتماعيات", related: "study_materials_c" },
    { word: "علم النفس", related: "study_materials_c" },
    { word: "علم الاجتماع", related: "study_materials_c" },
    { word: "تربية وطنية", related: "study_materials_c" },
    { word: "سياسة", related: "study_materials_c" },
    { word: "علوم سياسية", related: "study_materials_c" },
    { word: "آثار", related: "study_materials_c" },

    { word: "حاسب", related: "study_materials_d" },
    { word: "تقنية رقمية", related: "study_materials_d" },
    { word: "تربية فنية", related: "study_materials_d" },
    { word: "تربية بدنية", related: "study_materials_d" },

    { word: "طب", related: "study_materials_e" },
    { word: "هندسة", related: "study_materials_e" },
    { word: "قانون", related: "study_materials_e" },
    { word: "إدارة أعمال", related: "study_materials_e" },
    { word: "محاسبة", related: "study_materials_e" },
    { word: "تسويق", related: "study_materials_e" },
    { word: "إعلام", related: "study_materials_e" },
    { word: "اقتصاد", related: "study_materials_e" },
    { word: "صيدلة", related: "study_materials_e" },
    { word: "تمريض", related: "study_materials_e" }
  ],

  //تأليف
  "كلمات خاصة": []
};